import { useEffect, useRef, useState } from "react";
import { api } from "./api";

/**
 * Real peak data for a media asset, fetched at the width it will be drawn.
 *
 * The editor previously drew `18 + ((i * 31) % 68)` — a fixed sawtooth with no
 * relationship to the audio — which made choosing a clip boundary guesswork.
 * Peaks are generated by a background job, so this hook polls while that job is
 * still running and reports `ready: false` until it lands.
 */
export function usePeaks(
  mediaId: string | null,
  buckets: number,
  range?: { start: number; end: number },
) {
  const [peaks, setPeaks] = useState<number[]>([]);
  const [ready, setReady] = useState(false);
  const retryRef = useRef<number | null>(null);

  const start = range?.start;
  const end = range?.end;

  useEffect(() => {
    if (!mediaId) {
      setPeaks([]);
      setReady(false);
      return;
    }
    let cancelled = false;

    const load = () => {
      api
        .mediaPeaks(mediaId, buckets, start, end)
        .then((payload) => {
          if (cancelled) return;
          setPeaks(payload.peaks);
          setReady(payload.ready);
          // Back off while the waveform job works; it is seconds for a clip and
          // under a minute for a long episode.
          if (!payload.ready) {
            retryRef.current = window.setTimeout(load, 2500);
          }
        })
        .catch(() => {
          if (!cancelled) setReady(false);
        });
    };

    load();
    return () => {
      cancelled = true;
      if (retryRef.current !== null) window.clearTimeout(retryRef.current);
    };
  }, [mediaId, buckets, start, end]);

  return { peaks, ready };
}

/**
 * Draws a peak envelope as mirrored bars on a canvas.
 *
 * Canvas rather than one DOM node per bar: a 900-bucket waveform is 900 elements
 * React would diff on every drag frame.
 */
/**
 * What the live bars look like at one instant.
 *
 * The export draws a real spectrum from the audio. The preview cannot run an
 * analyser over a streamed file cheaply, so it fakes the *shape* — energy
 * falling off to the right, the way speech does on a log frequency scale —
 * and scales it by the true loudness at the playhead, which it does have from
 * the peak envelope. Close enough to judge placement and colour, which is
 * what the preview is for; the export is what it actually looks like.
 */
export type LiveBars = { level: number; tick: number; bins?: number };

function liveHeights(live: LiveBars): number[] {
  const bins = live.bins ?? 34;
  const heights: number[] = [];
  for (let index = 0; index < bins; index += 1) {
    // Deterministic per bar and per tick, so it flickers like a meter rather
    // than crawling like a scrolling waveform.
    const seed = Math.sin(index * 12.9898 + live.tick * 78.233) * 43758.5453;
    const noise = seed - Math.floor(seed);
    // Mirrored like the export: a mountain rising to the middle, not a
    // wedge leaning on the left edge.
    const centre = (bins - 1) / 2;
    const falloff = Math.pow(1 - Math.abs(index - centre) / (centre || 1), 1.4);
    heights.push(Math.max(0.04, live.level * (0.35 + 0.65 * noise) * (0.3 + 0.7 * falloff)));
  }
  return heights;
}

// How each style buckets and spaces its bars. Mirrors ENVELOPE_STYLES and
// PULSE_STYLES in backend/app/services/scene.py so the preview matches the
// export instead of showing one generic look for every choice.
const STYLE_SHAPES: Record<string, { bars: number; gap: number }> = {
  pulse: { bars: 34, gap: 0.33 },
  pulseFine: { bars: 52, gap: 0.3 },
  pulseChunky: { bars: 22, gap: 0.36 },
  envelope: { bars: 58, gap: 0.34 },
  envelopeFine: { bars: 104, gap: 0.28 },
  envelopeChunky: { bars: 34, gap: 0.4 },
  solid: { bars: 120, gap: 0 },
};

export function WaveformCanvas({
  peaks,
  ready,
  color = "#759a92",
  background = "transparent",
  className,
  live = null,
  styleId = "envelope",
}: {
  peaks: number[];
  ready: boolean;
  color?: string;
  background?: string;
  className?: string;
  /** When set, draw moving bars at this level instead of the still envelope. */
  live?: LiveBars | null;
  /** Which sound-bar style to mirror; see STYLE_SHAPES. */
  styleId?: string;
}) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const parent = canvas.parentElement;
    if (!parent) return;

    const draw = () => {
      const ratio = globalThis.devicePixelRatio || 1;
      const width = parent.clientWidth;
      const height = parent.clientHeight;
      if (width === 0 || height === 0) return;
      canvas.width = Math.round(width * ratio);
      canvas.height = Math.round(height * ratio);
      canvas.style.width = `${width}px`;
      canvas.style.height = `${height}px`;

      const context = canvas.getContext("2d");
      if (!context) return;
      context.setTransform(ratio, 0, 0, ratio, 0, 0);
      context.clearRect(0, 0, width, height);
      if (background !== "transparent") {
        context.fillStyle = background;
        context.fillRect(0, 0, width, height);
      }

      const middle = height / 2;
      if (live) {
        const heights = liveHeights(live);
        const pitch = width / heights.length;
        // Spaced like the style's still bars, so the live look differs per
        // style too and not only while paused.
        const share = (STYLE_SHAPES[styleId] ?? STYLE_SHAPES.pulse).gap;
        const gap = share === 0 ? 0 : Math.max(1, pitch * share);
        context.fillStyle = color;
        heights.forEach((value, index) => {
          const amplitude = Math.max(2, value * middle);
          context.fillRect(index * pitch, middle - amplitude, pitch - gap, amplitude * 2);
        });
        return;
      }
      if (peaks.length === 0) {
        // A flat line reads as "no data yet" rather than as silence.
        context.fillStyle = color;
        context.globalAlpha = ready ? 0.5 : 0.25;
        context.fillRect(0, middle - 1, width, 2);
        context.globalAlpha = 1;
        return;
      }

      // Bucket the peaks to the style's own bar count and spacing, with the
      // same normalising curve the renderer uses, so choosing a style in
      // the panel visibly changes the canvas — not just the export.
      const shape = STYLE_SHAPES[styleId] ?? STYLE_SHAPES.envelope;
      const pitch = width / shape.bars;
      const barWidth = Math.max(1, pitch * (1 - shape.gap));
      context.fillStyle = color;
      const loudest = Math.max(...peaks) || 1;
      const bucketStep = peaks.length / shape.bars;
      for (let index = 0; index < shape.bars; index += 1) {
        const from = Math.floor(index * bucketStep);
        const to = Math.max(Math.floor((index + 1) * bucketStep), from + 1);
        let bucket = 0;
        for (let k = from; k < to && k < peaks.length; k += 1) bucket = Math.max(bucket, peaks[k]);
        const scaled = Math.pow(Math.max(bucket, 0) / loudest, 0.65);
        const amplitude = Math.max(0.03, scaled) * middle;
        context.fillRect(index * pitch, middle - amplitude, barWidth, amplitude * 2);
      }
    };

    draw();
    const observer = new ResizeObserver(draw);
    observer.observe(parent);
    return () => observer.disconnect();
  }, [peaks, ready, color, background, live, styleId]);

  return <canvas className={className} ref={canvasRef} aria-hidden="true" />;
}
