import { useEffect, useRef, useState } from "react";
import { api } from "./api";

/**
 * Real peak data for a media asset, fetched at the width it will be drawn.
 *
 * The editor previously drew `18 + ((i * 31) % 68)` — a fixed sawtooth with no
 * relationship to the audio — which made choosing a clip boundary guesswork.
 * Peaks are generated by a background job, so this hook polls while that job is
 * still running and reports `ready: false` until it lands.
 */
export function usePeaks(
  mediaId: string | null,
  buckets: number,
  range?: { start: number; end: number },
) {
  const [peaks, setPeaks] = useState<number[]>([]);
  const [ready, setReady] = useState(false);
  const retryRef = useRef<number | null>(null);

  const start = range?.start;
  const end = range?.end;

  useEffect(() => {
    if (!mediaId) {
      setPeaks([]);
      setReady(false);
      return;
    }
    let cancelled = false;

    const load = () => {
      api
        .mediaPeaks(mediaId, buckets, start, end)
        .then((payload) => {
          if (cancelled) return;
          setPeaks(payload.peaks);
          setReady(payload.ready);
          // Back off while the waveform job works; it is seconds for a clip and
          // under a minute for a long episode.
          if (!payload.ready) {
            retryRef.current = window.setTimeout(load, 2500);
          }
        })
        .catch(() => {
          if (!cancelled) setReady(false);
        });
    };

    load();
    return () => {
      cancelled = true;
      if (retryRef.current !== null) window.clearTimeout(retryRef.current);
    };
  }, [mediaId, buckets, start, end]);

  return { peaks, ready };
}

/**
 * Draws a peak envelope as mirrored bars on a canvas.
 *
 * Canvas rather than one DOM node per bar: a 900-bucket waveform is 900 elements
 * React would diff on every drag frame.
 */
export function WaveformCanvas({
  peaks,
  ready,
  color = "#759a92",
  background = "transparent",
  className,
}: {
  peaks: number[];
  ready: boolean;
  color?: string;
  background?: string;
  className?: string;
}) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const parent = canvas.parentElement;
    if (!parent) return;

    const draw = () => {
      const ratio = globalThis.devicePixelRatio || 1;
      const width = parent.clientWidth;
      const height = parent.clientHeight;
      if (width === 0 || height === 0) return;
      canvas.width = Math.round(width * ratio);
      canvas.height = Math.round(height * ratio);
      canvas.style.width = `${width}px`;
      canvas.style.height = `${height}px`;

      const context = canvas.getContext("2d");
      if (!context) return;
      context.setTransform(ratio, 0, 0, ratio, 0, 0);
      context.clearRect(0, 0, width, height);
      if (background !== "transparent") {
        context.fillStyle = background;
        context.fillRect(0, 0, width, height);
      }

      const middle = height / 2;
      if (peaks.length === 0) {
        // A flat line reads as "no data yet" rather than as silence.
        context.fillStyle = color;
        context.globalAlpha = ready ? 0.5 : 0.25;
        context.fillRect(0, middle - 1, width, 2);
        context.globalAlpha = 1;
        return;
      }

      const step = width / peaks.length;
      const barWidth = Math.max(1, step - Math.min(1, step * 0.25));
      context.fillStyle = color;
      // Normalise against the loudest bucket with the same curve the renderer
      // uses, so the preview and the export show the same waveform. Speech
      // peaks well below full scale; drawing it raw is a flat line.
      const loudest = Math.max(...peaks) || 1;
      for (let index = 0; index < peaks.length; index += 1) {
        const scaled = Math.pow(Math.max(peaks[index], 0) / loudest, 0.65);
        const amplitude = Math.max(0.03, scaled) * middle;
        context.fillRect(
          index * step,
          middle - amplitude,
          barWidth,
          amplitude * 2,
        );
      }
    };

    draw();
    const observer = new ResizeObserver(draw);
    observer.observe(parent);
    return () => observer.disconnect();
  }, [peaks, ready, color, background]);

  return <canvas className={className} ref={canvasRef} aria-hidden="true" />;
}
